### ISSUE TITLE
Add error to temperatures

### ISSUE THREAD

**Issue by rumachan** [yannikbehr/Excel2FITS_macros#2]
After loading the latest batch of data I realised that, because analyte concentrations have no error information, we didn't implement this for the temperature data. For temperatures measured by thermocouple, which is what is always used, I assign an error of 2.2 deg, which is the error at 0 deg for the type of thermocouple used. Can we implement that?

**Comment by yannikbehr** [comment]
Done: https://github.com/yannikbehr/Excel2FITS_macros/commit/e9d6918aa9774aa8c24dbc424ee161cb0a874c17
